data:
  raw:
    file_client_profile: "../data/raw/df_final_demo.txt"
    file_experiment_clients: "../data/raw/df_final_experiment_clients.txt"
    file_web1: "../data/raw/df_final_web_data_pt_1.txt"
    file_web2: "../data/raw/df_final_web_data_pt_2.txt"
    file_footprints: "../data/raw/df_footprints.csv"
    file_demo_experiment: "../data/raw/df_final_demo_concat.csv"
  clean:
    file: "../data/clean/cleaned.csv"
    footprint_final_client_experiment_Cleaned: "../data/clean/final_client_experiment_Cleaned.csv"
    file_demo_experiment_cleaned: "../data/clean/df_final_demo_concat_cleaned.csv"
    file_footprints_transformed: "../data/clean/df_footprints_transformed.csv"
